### ISSUE TITLE
Update to Python 3.6

### ISSUE THREAD

**Issue by arfon** [spacetelescope/astropy-sep-lambda#4]
...it's the future.

**Comment by nmiles2718** [comment]
@arfon I have a [python 3.6 version of this](https://github.com/nmiles2718/astropy-build-lambda/blob/hstcal-build-lambda/py3build.sh) and I intend on submitting a PR to this repo containing those updates. I have tested it with my own lambda function and it builds properly (yay for no import errors!). I would submit a PR now, but currently the build script is setup for my specific python modules (copies over more files instead of just `process.py`, see eg [updated L46](https://github.com/nmiles2718/astropy-build-lambda/blob/d8aa37c8557024c8566601753c414df8c04a719e/py3build.sh#L46) vs. [original L46](https://github.com/spacetelescope/astropy-sep-lambda/blob/7ae311bb14475909a12e97bc14269d19d675234c/build.sh#L46)

I plan on updating the docker AMI as well
- I've been using amazonlinux:2018.03 and it works great. I haven't really found a great resource for determining what versions exist. The 2018.03 number came straight from the list of AMIs in the EC2 console when you select "Launch Instance".

**Comment by arfon** [comment]
Awesome! Thanks for working on this - I'd love to update this function for Python 3.6.

Perhaps [your version](https://github.com/nmiles2718/astropy-build-lambda/blob/d8aa37c8557024c8566601753c414df8c04a719e/py3build.sh#L46) is more generically useful to others?

**Comment by nmiles2718** [comment]
Cool, my goal is to have the PR submitted before the new year to beat the 2020 Python2 deadline 👍.

Yeah, I think it would be _very_ useful to have a generic version laying around somewhere, but that's only half the battle. I think the biggest problem everyone has is dealing with super-user privileges required by `docker` and I don't know of a straightforward way to circumvent that. The best solution I've found so far is to launch a `t2.mirco`, install `docker` and then create the container on the instance. I think it would be very useful if we had a blog post showing how to use the build script in a general sense. Thoughts?

**Comment by arfon** [comment]
> I think it would be very useful if we had a blog post showing how to use the build script is a general sense. Thoughts?

Is this because STScI-owned laptops don't allow you to build this locally?

**Comment by nmiles2718** [comment]
Yeah, installing docker and configuring it requires super-user privileges. I think there might be a way for IT to install docker on our laptops, then do something [along these lines](https://docs.docker.com/install/linux/linux-postinstall/) to circumvent the issue.

**Comment by arfon** [comment]
Ah OK, thanks for clarifying.

> I think it would be very useful if we had a blog post showing how to use the build script is a general sense. Thoughts?

I kind of have mixed emotions about this, especially as this is a self-inflicted issue by STScI. Most people can simply do:

```
$ docker pull amazonlinux:2017.09
$ docker run -v $(pwd):/outputs -it amazonlinux:2017.09 /bin/bash /outputs/build.sh
```

(or something similar).

Isn't the easiest resolution here to get ITSD to install Docker?

**Comment by nmiles2718** [comment]
Yeah, I agree. My only suggesting is to update to `amazonlinux:2018.03` 

```console
$ docker pull amazonlinux:2018.03
$ docker run -v $(pwd):/outputs -it amazonlinux:2018.03 /bin/bash /outputs/build.sh
```
Haha definitely. But, I think there might also be a way to do this so that everything is executed at the command line from your laptop. This would be pretty cool because then the only thing transferred over the network are the commands to the `EC2` instance. Once the container finishes building, you can just upload it to `S3` and link it to the corresponding lambda function. As I write this, I now realize this is what [serverless](https://serverless.com/framework/docs/providers/aws/) does for you lol.
